USE projet_bdr;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Concerner;
DROP TABLE IF EXISTS Offre;
DROP TABLE IF EXISTS Evaluation;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Chambre;
DROP TABLE IF EXISTS Prestation;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Type_Chambre;
DROP TABLE IF EXISTS Hotel;

SET FOREIGN_KEY_CHECKS = 1;
